/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Configuration for opening a DeltaDb instance. */
export interface DeltaDbConfig {
  /** SQL schema definition string. */
  schema: string
  /**
   * Path to RocksDB data directory for persistence.
   * When omitted, uses in-memory storage (data lost on restart).
   */
  dataDir?: string
  /** Maximum buffer size before backpressure (default: 10000). */
  maxBufferSize?: number
}
/** Block cursor: number + hash. */
export interface DeltaDbCursor {
  number: number
  hash: string
}
/** Input for the atomic `ingest()` method. */
export interface IngestInput {
  /** Table name → rows, msgpack-encoded as `{tableName: [{col: val}, ...], ...}`. */
  data: Buffer
  /** Unfinalized blocks with hashes for fork resolution. */
  rollbackChain?: Array<DeltaDbCursor>
  /** Finalized head cursor — both number and hash stored. */
  finalizedHead: DeltaDbCursor
}
/** State field definition for external reducers. */
export interface ExternalStateField {
  name: string
  /** Column type: "Float64", "UInt64", "Int64", "String", "Boolean", "Json" */
  columnType: string
  /** Default value as a string literal (e.g., "0", "'hello'", "{}") */
  defaultValue: string
}
/** Configuration for registering an external reducer. */
export interface ExternalReducerConfig {
  name: string
  source: string
  groupBy: Array<string>
  state: Array<ExternalStateField>
}
/** Delta DB N-API wrapper. */
export declare class DeltaDb {
  /** Open a new DeltaDb instance. */
  static open(config: DeltaDbConfig): DeltaDb
  /**
   * Register an external reducer with a JS batch callback.
   *
   * The callback receives an array of `{ state, rows }` groups and must
   * return an array of `{ state, emits }` results (same length, same order).
   *
   * Must be called before any `processBatch` or `ingest` calls.
   */
  registerReducer(config: ExternalReducerConfig, callback: (...args: any[]) => any): void
  /**
   * Atomic ingest: process all tables, store rollback chain, finalize, flush.
   * Returns a msgpack-encoded DeltaBatch buffer, or null if no records produced.
   */
  ingest(input: IngestInput): Buffer | null
  /**
   * Find the common ancestor between our state and the Portal's chain.
   * Returns the matching block cursor, or null if no common ancestor found.
   */
  resolveForkCursor(previousBlocks: Array<DeltaDbCursor>): DeltaDbCursor | null
  /**
   * Flush buffered deltas into a msgpack-encoded batch.
   * Returns null if no pending records.
   */
  flush(): Buffer | null
  /** Acknowledge a flushed batch by sequence number. */
  ack(sequence: number): void
  /** Number of pending (unflushed) delta records. */
  get pendingCount(): number
  /** Whether backpressure should be applied. */
  get isBackpressured(): boolean
  /** Current cursor: latest processed block + hash. Null if no blocks processed. */
  get cursor(): DeltaDbCursor | null
}
